/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CrowdfundingInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "campaignCount" | "campaigns" | "claimRefund" | "contributions" | "createCampaign" | "donate" | "finalizeCampaign" | "forceFailCampaign" | "pauseCampaign" | "resumeCampaign" | "setVerifiedRecipient" | "verifiedRecipients"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated" | "CampaignFailed" | "CampaignPaused" | "CampaignResumed" | "CampaignSuccessful" | "DonationReceived" | "RefundIssued"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'donate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'forceFailCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resumeCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setVerifiedRecipient', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'verifiedRecipients', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'forceFailCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resumeCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setVerifiedRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiedRecipients', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [campaignId: BigNumberish, creator: AddressLike, recipient: AddressLike, goal: BigNumberish, deadline: BigNumberish, isVerifiedRecipient: boolean];
      export type OutputTuple = [campaignId: bigint, creator: string, recipient: string, goal: bigint, deadline: bigint, isVerifiedRecipient: boolean];
      export interface OutputObject {campaignId: bigint, creator: string, recipient: string, goal: bigint, deadline: bigint, isVerifiedRecipient: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignFailedEvent {
      export type InputTuple = [campaignId: BigNumberish];
      export type OutputTuple = [campaignId: bigint];
      export interface OutputObject {campaignId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignPausedEvent {
      export type InputTuple = [campaignId: BigNumberish];
      export type OutputTuple = [campaignId: bigint];
      export interface OutputObject {campaignId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignResumedEvent {
      export type InputTuple = [campaignId: BigNumberish];
      export type OutputTuple = [campaignId: bigint];
      export interface OutputObject {campaignId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignSuccessfulEvent {
      export type InputTuple = [campaignId: BigNumberish];
      export type OutputTuple = [campaignId: bigint];
      export interface OutputObject {campaignId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DonationReceivedEvent {
      export type InputTuple = [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, donor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundIssuedEvent {
      export type InputTuple = [campaignId: BigNumberish, donor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, donor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, donor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Crowdfunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): Crowdfunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, boolean] & {creator: string, recipient: string, goal: bigint, deadline: bigint, totalRaised: bigint, status: bigint, isVerifiedRecipient: boolean }],
      'view'
    >
    

    
    claimRefund: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [recipient: AddressLike, goal: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    donate: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    finalizeCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    forceFailCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pauseCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resumeCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setVerifiedRecipient: TypedContractMethod<
      [recipient: AddressLike, isVerified: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    verifiedRecipients: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, boolean] & {creator: string, recipient: string, goal: bigint, deadline: bigint, totalRaised: bigint, status: bigint, isVerifiedRecipient: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [recipient: AddressLike, goal: BigNumberish, deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'donate'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'finalizeCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'forceFailCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resumeCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setVerifiedRecipient'): TypedContractMethod<
      [recipient: AddressLike, isVerified: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifiedRecipients'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'CampaignFailed'): TypedContractEvent<CampaignFailedEvent.InputTuple, CampaignFailedEvent.OutputTuple, CampaignFailedEvent.OutputObject>;
getEvent(key: 'CampaignPaused'): TypedContractEvent<CampaignPausedEvent.InputTuple, CampaignPausedEvent.OutputTuple, CampaignPausedEvent.OutputObject>;
getEvent(key: 'CampaignResumed'): TypedContractEvent<CampaignResumedEvent.InputTuple, CampaignResumedEvent.OutputTuple, CampaignResumedEvent.OutputObject>;
getEvent(key: 'CampaignSuccessful'): TypedContractEvent<CampaignSuccessfulEvent.InputTuple, CampaignSuccessfulEvent.OutputTuple, CampaignSuccessfulEvent.OutputObject>;
getEvent(key: 'DonationReceived'): TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
getEvent(key: 'RefundIssued'): TypedContractEvent<RefundIssuedEvent.InputTuple, RefundIssuedEvent.OutputTuple, RefundIssuedEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(uint256,address,address,uint256,uint256,bool)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'CampaignFailed(uint256)': TypedContractEvent<CampaignFailedEvent.InputTuple, CampaignFailedEvent.OutputTuple, CampaignFailedEvent.OutputObject>;
      CampaignFailed: TypedContractEvent<CampaignFailedEvent.InputTuple, CampaignFailedEvent.OutputTuple, CampaignFailedEvent.OutputObject>;
    

      'CampaignPaused(uint256)': TypedContractEvent<CampaignPausedEvent.InputTuple, CampaignPausedEvent.OutputTuple, CampaignPausedEvent.OutputObject>;
      CampaignPaused: TypedContractEvent<CampaignPausedEvent.InputTuple, CampaignPausedEvent.OutputTuple, CampaignPausedEvent.OutputObject>;
    

      'CampaignResumed(uint256)': TypedContractEvent<CampaignResumedEvent.InputTuple, CampaignResumedEvent.OutputTuple, CampaignResumedEvent.OutputObject>;
      CampaignResumed: TypedContractEvent<CampaignResumedEvent.InputTuple, CampaignResumedEvent.OutputTuple, CampaignResumedEvent.OutputObject>;
    

      'CampaignSuccessful(uint256)': TypedContractEvent<CampaignSuccessfulEvent.InputTuple, CampaignSuccessfulEvent.OutputTuple, CampaignSuccessfulEvent.OutputObject>;
      CampaignSuccessful: TypedContractEvent<CampaignSuccessfulEvent.InputTuple, CampaignSuccessfulEvent.OutputTuple, CampaignSuccessfulEvent.OutputObject>;
    

      'DonationReceived(uint256,address,uint256)': TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
      DonationReceived: TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
    

      'RefundIssued(uint256,address,uint256)': TypedContractEvent<RefundIssuedEvent.InputTuple, RefundIssuedEvent.OutputTuple, RefundIssuedEvent.OutputObject>;
      RefundIssued: TypedContractEvent<RefundIssuedEvent.InputTuple, RefundIssuedEvent.OutputTuple, RefundIssuedEvent.OutputObject>;
    
    };
  }